### ISSUE TITLE
Cannot send headers; headers already sent

### ISSUE THREAD

**Issue by chackskovic** [meabed/Groupon-Clone-On-Magento#3]
Hie all, please help I am getting this error:

Cannot send headers; headers already sent in /home/chacks/public_html/demo2/app/Mage.php, line 767

Trace:
#0 /home/chacks/public_html/demo2/lib/Zend/Controller/Response/Abstract.php(115): Zend_Controller_Response_Abstract->canSendHeaders(true)
#1 /home/chacks/public_html/demo2/app/code/core/Mage/Core/Model/App.php(1246): Zend_Controller_Response_Abstract->setHeader('Content-Type', 'text/html; char...')
#2 /home/chacks/public_html/demo2/app/code/core/Mage/Core/Controller/Varien/Front.php(80): Mage_Core_Model_App->getResponse()
#3 /home/chacks/public_html/demo2/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(202): Mage_Core_Controller_Varien_Front->getResponse()
#4 /home/chacks/public_html/demo2/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#5 /home/chacks/public_html/demo2/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#6 /home/chacks/public_html/demo2/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#7 /home/chacks/public_html/demo2/index.php(87): Mage::run('', 'store')
#8 {main}

help please!!

**Comment by deckside** [comment]
I have the same issue. 

Did you find a fix?

thank you in advance

**Comment by chackskovic** [comment]
ended up getting another groupon clone..was easier than finding a solution to this.

**Comment by kleyntjies** [comment]
What groupon clone did you use? I am looking for one?

**Comment by chackskovic** [comment]
two options:

1) http://grouponclone.contus.com/

or

2) adolstore.com

**Comment by kleyntjies** [comment]
Don’t you have a copy I could get? I don’t want to pay for one. Stay in South africa and the exchange rate makes it expensive to buy… Or do you know of any free ones I could download?

Kind regards,
Rihan Kleyn
083 297 7070
rihankleyn@me.com <mailto:rihankleyn@me.com>
